name: Build&Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master, testing ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.19', '1.20', '1.21', '1.22', '1.23', '1.24' ]

    name: Setup Go ${{ matrix.go }} environment
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: |
        go get -u golang.org/x/lint/golint
    - name: Lint
      run: golint ./...

    - name: Vet
      run: go vet ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v -cover ./...
